//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبارسنجی انجام نشد.
        /// </summary>
        public static string authenticate_failure {
            get {
                return ResourceManager.GetString("authenticate_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد حساب شوید.
        /// </summary>
        public static string authentication_failed {
            get {
                return ResourceManager.GetString("authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This token has no claims.
        /// </summary>
        public static string token_has_no_claims {
            get {
                return ResourceManager.GetString("token_has_no_claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This token has no secuirty stamp.
        /// </summary>
        public static string token_has_no_secuirty_stamp {
            get {
                return ResourceManager.GetString("token_has_no_secuirty_stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی وجود ندارد.
        /// </summary>
        public static string unauthorized_access_resource {
            get {
                return ResourceManager.GetString("unauthorized_access_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری غیر فعال است.
        /// </summary>
        public static string user_notactive {
            get {
                return ResourceManager.GetString("user_notactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا گذرواژه اشتباه میباشد.
        /// </summary>
        public static string username_password_notvalid {
            get {
                return ResourceManager.GetString("username_password_notvalid", resourceCulture);
            }
        }
    }
}
